drop table if  exists   meifu_analysis_platform_main_2023;
	create table if not exists  meifu_analysis_platform_main_2023 as 
	select 
		auto_id
		,title
		,is_comment
		,webpageUrl
		,captureWebsiteNew
		,publishedMinute
		,originType
		,author
		,summary
		,province
		,city
		,originTypeThird
		,secondTradeList
		,originAuthorId
		,referenceKeywordNew
		,shareCount
		,comments
		,praiseNum
		,forwardNumber
		,favouritesCount
		,fansNumber
		,friendsCount
		,gender
		,icpProvince
		,id
		,publishedDay
		,readCount
		,subDomain
		,titleHs
		,topicInteractionCount
		,weiboTopicKeyword
		,weiboUserBeanNew
		,zaikanCount
		,create_date
		,description
		,content
		,referenceKeyword
		,project_name
	from data_23q3_1 ;

insert into meifu_analysis_platform_main_2023(
		auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
)
select 
	auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
from data_23q3_2 ;

insert into meifu_analysis_platform_main_2023(
		auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
)
select 
	auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
from data_23q4_1 ;

insert into meifu_analysis_platform_main_2023(
		auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
)
select 
	auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
from data_23q4_2 ;

insert into meifu_analysis_platform_main_2023(
		auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
)
select 
	auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
from data_23q4_3 ;

insert into meifu_analysis_platform_main_2023(
		auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
)
select 
	auto_id
	,title
	,is_comment
	,webpageUrl
	,captureWebsiteNew
	,publishedMinute
	,originType
	,author
	,summary
	,province
	,city
	,originTypeThird
	,secondTradeList
	,originAuthorId
	,referenceKeywordNew
	,shareCount
	,comments
	,praiseNum
	,forwardNumber
	,favouritesCount
	,fansNumber
	,friendsCount
	,gender
	,icpProvince
	,id
	,publishedDay
	,readCount
	,subDomain
	,titleHs
	,topicInteractionCount
	,weiboTopicKeyword
	,weiboUserBeanNew
	,zaikanCount
	,create_date
	,description
	,content
	,referenceKeyword
	,project_name
from data_23q4_4 ;